### ISSUE TITLE
How did you get the SMPLX of the MultiHuman datasets

### ISSUE THREAD

**Issue by chingswy** [y-zheng18/MultiHuman-Dataset#7]
I visualized `MultiHuman/three/[500,502]` sequence, it seems that some body parts of smplx are misaligned with the textured mesh. Did you use ICP or markerless mocap to get the SMPLX results?

![dingtalkgov_qt_clipbord_pic_2](https://user-images.githubusercontent.com/22812405/193998107-96197826-3580-4123-b8ab-d9d621cc8072.png)
![lQLPJxa_0bc7IufNAeDNAxmwXanuKLq8XhoDO1fGaAAFAA_793_480](https://user-images.githubusercontent.com/22812405/193998133-c77d073f-3ade-49ad-bf2b-3364a0519b75.png)

**Comment by y-zheng18** [comment]
Since the dataset is originally used to test the accuracy of multiview human reconstruction algorithms, the smplx models are fit simply by detecting keypoints from 6 views. Thus, in some multiperson cases the fitting may not be accurate. We don't use ICP or markerless mocap. But if you want to get more accurate results, surely you can include ICP and many other algorithms.

**Comment by chingswy** [comment]
Thanks!
